version: 2

models:
  - name: results
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
  - name: circuits
    description: "A View with corrected circuits information"
